-- ============================================================
-- ILMCS Seed Data: All 56 Industrial Regions
-- ============================================================

-- NEW INDUSTRIAL AREAS (36)
INSERT INTO industrial_region (name, code, type, state, district) VALUES
('KHAPRI KHURD', 'KHAPRI_KHURD', 'NEW', 'Chhattisgarh', 'Raipur'),
('NARAYANBAHALI', 'NARAYANBAHALI', 'NEW', 'Chhattisgarh', 'Raipur'),
('AURETHI, BHATAPARA', 'AURETHI_BHATAPARA', 'NEW', 'Chhattisgarh', 'Balodabazar'),
('SIYARPALI-MAHUAPALI', 'SIYARPALI_MAHUAPALI', 'NEW', 'Chhattisgarh', 'Raigarh'),
('RIKHI', 'RIKHI', 'NEW', 'Chhattisgarh', 'Raipur'),
('METAL PARK PHASE II SECTOR A', 'METAL_PARK_2A', 'NEW', 'Chhattisgarh', 'Raipur'),
('FOOD PARK SECTOR 1', 'FOOD_PARK_S1', 'NEW', 'Chhattisgarh', 'Raipur'),
('PANGRIKHURD', 'PANGRIKHURD', 'NEW', 'Chhattisgarh', 'Raipur'),
('BARBASPUR', 'BARBASPUR', 'NEW', 'Chhattisgarh', 'Raipur'),
('GANGAPUR KHURD AMBIKAPUR', 'GANGAPUR_KHURD', 'NEW', 'Chhattisgarh', 'Surguja'),
('TEXTILE PARK', 'TEXTILE_PARK', 'NEW', 'Chhattisgarh', 'Raipur'),
('METAL PARK PHASE II SECTOR B', 'METAL_PARK_2B', 'NEW', 'Chhattisgarh', 'Raipur'),
('TILDA', 'TILDA', 'NEW', 'Chhattisgarh', 'Raipur'),
('Industrial Area Abhanpur', 'IA_ABHANPUR', 'NEW', 'Chhattisgarh', 'Raipur'),
('TEKNAR', 'TEKNAR', 'NEW', 'Chhattisgarh', 'Raipur'),
('LAKHANPURI', 'LAKHANPURI', 'NEW', 'Chhattisgarh', 'Raipur'),
('HATHKERA-BIDBIDA', 'HATHKERA_BIDBIDA', 'NEW', 'Chhattisgarh', 'Raipur'),
('KESDA', 'KESDA', 'NEW', 'Chhattisgarh', 'Raipur'),
('ENGINEERING PARK', 'ENGINEERING_PARK', 'NEW', 'Chhattisgarh', 'Raipur'),
('SILPAHARI INDUSTRIAL AREA', 'SILPAHARI_IA', 'NEW', 'Chhattisgarh', 'Raipur'),
('PARASGARHI INDUSTRIAL AREA', 'PARASGARHI_IA', 'NEW', 'Chhattisgarh', 'Raipur'),
('FOOD PARK SECTOR 2', 'FOOD_PARK_S2', 'NEW', 'Chhattisgarh', 'Raipur'),
('MAHROOMKHURD', 'MAHROOMKHURD', 'NEW', 'Chhattisgarh', 'Raipur'),
('RAIL PARK', 'RAIL_PARK', 'NEW', 'Chhattisgarh', 'Raipur'),
('KHAMARIA INDUSTRIAL AREA', 'KHAMARIA_IA', 'NEW', 'Chhattisgarh', 'Raipur'),
('READYMADE GARMENTS PARK NAVA RAIPUR', 'RMG_PARK_NR', 'NEW', 'Chhattisgarh', 'Raipur'),
('PHARMACEUTICAL PARK NAVA RAIPUR', 'PHARMA_PARK_NR', 'NEW', 'Chhattisgarh', 'Raipur'),
('Industrial Area G-Jamgoan', 'IA_GJAMGOAN', 'NEW', 'Chhattisgarh', 'Raipur'),
('FARSABAHAR', 'FARSABAHAR', 'NEW', 'Chhattisgarh', 'Jashpur'),
('PLASTIC PARK', 'PLASTIC_PARK', 'NEW', 'Chhattisgarh', 'Raipur'),
('Industrial Area Selar', 'IA_SELAR', 'NEW', 'Chhattisgarh', 'Raipur'),
('Industrial Area Shyamtarai', 'IA_SHYAMTARAI', 'NEW', 'Chhattisgarh', 'Raipur'),
('Food Park Sukma', 'FOOD_PARK_SUKMA', 'NEW', 'Chhattisgarh', 'Sukma'),
('ULAKIYA', 'ULAKIYA', 'NEW', 'Chhattisgarh', 'Raipur'),
('Industrial Area Cum Food Park Chandanu Raveli', 'IA_CHANDANU', 'NEW', 'Chhattisgarh', 'Raipur'),
('PARASIYA', 'PARASIYA', 'NEW', 'Chhattisgarh', 'Raipur');

-- OLD INDUSTRIAL AREAS (20)
INSERT INTO industrial_region (name, code, type, state, district) VALUES
('AMASEONI', 'AMASEONI', 'OLD', 'Chhattisgarh', 'Raipur'),
('BHANPURI', 'BHANPURI', 'OLD', 'Chhattisgarh', 'Raipur'),
('BIRKONI', 'BIRKONI', 'OLD', 'Chhattisgarh', 'Raipur'),
('BORAI', 'BORAI', 'OLD', 'Chhattisgarh', 'Durg'),
('ELECTRONIC EMC', 'ELECTRONIC_EMC', 'OLD', 'Chhattisgarh', 'Raipur'),
('GOGOAN', 'GOGOAN', 'OLD', 'Chhattisgarh', 'Raipur'),
('GONDWARA', 'GONDWARA', 'OLD', 'Chhattisgarh', 'Raipur'),
('HARINCHHAPARA', 'HARINCHHAPARA', 'OLD', 'Chhattisgarh', 'Raipur'),
('KAPAN', 'KAPAN', 'OLD', 'Chhattisgarh', 'Raipur'),
('NAYANPUR-GIBARGANJ', 'NAYANPUR_GIBARGANJ', 'OLD', 'Chhattisgarh', 'Raipur'),
('RANIDURGAWATI ANJANI', 'RANIDURGAWATI', 'OLD', 'Chhattisgarh', 'Raipur'),
('RAWABHATA', 'RAWABHATA', 'OLD', 'Chhattisgarh', 'Raipur'),
('SILTARA PHASE 1', 'SILTARA_P1', 'OLD', 'Chhattisgarh', 'Raipur'),
('SILTARA PHASE 2', 'SILTARA_P2', 'OLD', 'Chhattisgarh', 'Raipur'),
('SIRGITTI', 'SIRGITTI', 'OLD', 'Chhattisgarh', 'Bilaspur'),
('SONDONGARI', 'SONDONGARI', 'OLD', 'Chhattisgarh', 'Raipur'),
('TENDUA PHASE 1', 'TENDUA_P1', 'OLD', 'Chhattisgarh', 'Raipur'),
('TENDUA PHASE 2', 'TENDUA_P2', 'OLD', 'Chhattisgarh', 'Raipur'),
('TIFRA', 'TIFRA', 'OLD', 'Chhattisgarh', 'Bilaspur'),
('URLA', 'URLA', 'OLD', 'Chhattisgarh', 'Raipur');
